services:
  app:
    image: node:20-alpine
    command: sh -c "node dist/server.js"
    ports:
      - 8080:80
    working_dir: /app
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./:/app
    environment:
      PORT: 80
      NODE_ENV: production
